### PR TITLE
Move license into crate

### PR DESCRIPTION
**Pull request by davidpdrsn**
Fixes https://github.com/tower-rs/tower-http/issues/153

### CODE REVIEW

**Comment by seanmonstar** [comment]
Usually you want a license in the root (too), implying it applies to all in the repo (examples, docs, etc).

**Comment by davidpdrsn** [comment]
@seanmonstar how do you tell cargo where to find the license then?

**Comment by seanmonstar** [comment]
This is the options I've seen:

- Just have 1 `Cargo.toml`, and a `src` directory at the root. Having it inside an extra directory I usually only see when there's multiple crates in a repository.
- If a repo has multiple crates, then the license file is sometimes symlinked into the other directories.
- Or, looks like the Tokio repo just puts a full copy in each place.

**Comment by davidpdrsn** [comment]
Yep I looked at tokio when I fixed it in axum as well. Kinda think I just wanna do that as its easy.

I think when setting up the repo I didn't realize you could have a workspace with one of the crates being in the root of the repo. It could be converted to that. I don't plan on having multiple published crates in this repo.

**Review by LucioFranco — APPROVED** [review]

**Pull request merged**
