### PR TITLE
Fix sensitive value leak

### PR DESCRIPTION
**Pull request by quininer**
Fix https://github.com/tower-rs/tower-http/issues/293

### CODE REVIEW

**Review by jplatte — APPROVED** [review]
LGTM, but I'll let sbd. else have a look too and execute the merge.

**Review by davidpdrsn — COMMENTED** [review]
Thanks!

Wanna add a test as well?

**Comment by quininer** [comment]
@davidpdrsn I added the relevant regression tests.

**Review by davidpdrsn — APPROVED** [review]
Thanks!

**Review by Nehliin — APPROVED** [review]

**Pull request merged**
