### PR TITLE
Properly support HEAD requests for ServeFile/ServeDir

### PR DESCRIPTION
**Pull request by Nehliin**
## Motivation
Fixes: https://github.com/tower-rs/tower-http/issues/113

## Solution
Looks at the metadata to determine the `Content-length` which is set as an additional header in the response. The response contains no body as expected for `HEAD` requests. It uses the same fallback strategy we use for opening files based on negotiated encoding to figure out which metadata should be read.

### CODE REVIEW

**Review by davidpdrsn — APPROVED** [review]
LGTM!

Is `HEAD` requests something to consider for [range request](https://github.com/tower-rs/tower-http/pull/173)? Might user agents send a `HEAD` request to check if the server supports range requests?

cc @MarcusGrass

**Comment by Nehliin** [comment]
@davidpdrsn yeah I would presume that would be one of the main use cases for `HEAD` requests

**Comment by MarcusGrass** [comment]
> LGTM!
> 
> Is `HEAD` requests something to consider for [range request](https://github.com/tower-rs/tower-http/pull/173)? Might user agents send a `HEAD` request to check if the server supports range requests?
> 
> cc @MarcusGrass

Yeah we do wan't that, I implemented it in read_partial then axed that when I heard that Oscar was doing something with HEAD, it's easy to add though!

**Comment by davidpdrsn** [comment]
Alright. Then lets get this merged and make any necessary adjustments in https://github.com/tower-rs/tower-http/pull/173.

**Comment by Nehliin** [comment]
👍 Could we merge #178 first to avoid extra conflicts?

**Comment by Nehliin** [comment]
Rebased now and added some extra tests. It should now use the same fallback strategy like we use for opening files based on negotiated encoding.

**Review by davidpdrsn — APPROVED** [review]

**Pull request merged**
