### PR TITLE
Update compression dependencies

### PR DESCRIPTION
**Pull request by tottoto**
## Motivation

Updates the dependencies related to compression.

## Solution

Updates to `async-compression` 0.4 and `zstd`  0.12.

### CODE REVIEW

**Comment by tottoto** [comment]
Tries to fix the ci at #372.

**Comment by Nehliin** [comment]
This seems to be a breaking change so could you add it to the changelog as well?

**Comment by tottoto** [comment]
Updated the changelog.

**Review by Nehliin — APPROVED** [review]

**Comment by tottoto** [comment]
Resolved a conflict.

**Pull request merged**
