### PR TITLE
Fix path normalization of index route

### LINKED ISSUE #318: Index route returns 404 with `NormalizePath` middleware
## Bug Report
Versions:
`tower-http = "0.3.5"`
`axum = "0.6.1"`

`Axum` "/" route doesn't work (returns 404) with `NormalizePath` middleware

``` rust
#[tokio::main]
async fn main() {
    let app = NormalizePath::trim_trailing_slash(
        Router::new()
            .route("/", get(|| async { "index" }))
            .route("/other", get(|| async { "other" }))
    );

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    axum::Server::bind(&addr).serve(app.into_make_service()).await.expect("Failed to start axum server");
}
```

### PR DESCRIPTION
**Pull request by cassaundra**
Previously, `normalize_path` on `/` would result in an empty string, causing routers to return 404 on the index route. Fix this by defaulting to `/` if the resultant path would be empty.

Fixes #318.

### CODE REVIEW

**Comment by cassaundra** [comment]
I just added an improved implementation which also removes multiple trailing slashes in the case of an index (e.g. `////` to `/`).

**Review by Nehliin — COMMENTED** [review]
I don't mind the solution of adding a "/" but it feels wrong to do this within a function called `remove_trailing_slash`. Could this logic be extracted to before calling into the method? If not we should at least rename the function

**Comment by cassaundra** [comment]
How about `normalize_trailing_slash`?

**Review by Nehliin — APPROVED** [review]
Thanks

**Pull request merged**
