### PR TITLE
Add support for private network preflights

### LINKED ISSUE #314: Support for Access-Control-Allow-Private-Network
### Motivation

Chrome is removing/has removed the ability to send requests to private network endpoints from public websites:
https://developer.chrome.com/blog/private-network-access-preflight/

There is a pre-flight header it sends now (`Access-Control-Request-Private-Network`) and expects in the response to allow those requests through.

### Proposal

Perhaps a new method alongside `allow_headers`/`allow_methods`/etc on `CorsLayer` (`allow_private_network_access`?) that provides the correct response header for the preflight request?

### PR DESCRIPTION
**Pull request by jplatte**
Fixes #314.

Needs a test, but I don't want to put in more time. Would be happy for somebody else to take over.

### CODE REVIEW

**Review by Nehliin — CHANGES_REQUESTED** [review]
Some unit tests would be nice for this as well just as a sanity check

**Comment by jplatte** [comment]
I don't really want to dedicate more time to this beyond fixing trivial things. Should we add help-wanted somewhere so somebody else can take this over?

**Comment by Nehliin** [comment]
Fair enough, sure that could make sense

**Comment by jplatte** [comment]
Done in #373.

**Pull request closed without merging**
